/*
 * API Identity Data
 * <p>Identity Data API es un facilitador de funcionalidades que engloba información de distintas fuentes de acceso públicas y privadas en el progreso del producto para realizar la validación de identidad del Cliente. El objetivo es que a través de una sola API, el usuario puede acceder, corroborar y validar la identidad de la persona haciendo la solicitud de un producto o servicio.</p><br/>
 *
 * OpenAPI spec version: 1.0
 * Contact: api@circulodecredito.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.identityData.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * CURPStatus
 */


public class CURPStatus {
  @SerializedName("statusOper")
  private String statusOper = null;

  @SerializedName("message")
  private String message = null;

  @SerializedName("tipoError")
  private String tipoError = null;

  @SerializedName("codigoError")
  private String codigoError = null;

  @SerializedName("sessionID")
  private String sessionID = null;

  @SerializedName("resultCURPS")
  private ResultCURPS resultCURPS = null;

  public CURPStatus statusOper(String statusOper) {
    this.statusOper = statusOper;
    return this;
  }

   /**
   * Get statusOper
   * @return statusOper
  **/
  @Schema(example = "EXITOSO", description = "")
  public String getStatusOper() {
    return statusOper;
  }

  public void setStatusOper(String statusOper) {
    this.statusOper = statusOper;
  }

  public CURPStatus message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  @Schema(example = "LA OPERACION SE EJECUTO.", description = "")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public CURPStatus tipoError(String tipoError) {
    this.tipoError = tipoError;
    return this;
  }

   /**
   * Get tipoError
   * @return tipoError
  **/
  @Schema(description = "")
  public String getTipoError() {
    return tipoError;
  }

  public void setTipoError(String tipoError) {
    this.tipoError = tipoError;
  }

  public CURPStatus codigoError(String codigoError) {
    this.codigoError = codigoError;
    return this;
  }

   /**
   * Get codigoError
   * @return codigoError
  **/
  @Schema(description = "")
  public String getCodigoError() {
    return codigoError;
  }

  public void setCodigoError(String codigoError) {
    this.codigoError = codigoError;
  }

  public CURPStatus sessionID(String sessionID) {
    this.sessionID = sessionID;
    return this;
  }

   /**
   * Get sessionID
   * @return sessionID
  **/
  @Schema(example = "y7H8d_Z-4u685On5rnq6YY3syZGKm2GH16UtpY8_2CMdKCbYZy6q!1654132111!1537539044990", description = "")
  public String getSessionID() {
    return sessionID;
  }

  public void setSessionID(String sessionID) {
    this.sessionID = sessionID;
  }

  public CURPStatus resultCURPS(ResultCURPS resultCURPS) {
    this.resultCURPS = resultCURPS;
    return this;
  }

   /**
   * Get resultCURPS
   * @return resultCURPS
  **/
  @Schema(description = "")
  public ResultCURPS getResultCURPS() {
    return resultCURPS;
  }

  public void setResultCURPS(ResultCURPS resultCURPS) {
    this.resultCURPS = resultCURPS;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CURPStatus cuRPStatus = (CURPStatus) o;
    return Objects.equals(this.statusOper, cuRPStatus.statusOper) &&
        Objects.equals(this.message, cuRPStatus.message) &&
        Objects.equals(this.tipoError, cuRPStatus.tipoError) &&
        Objects.equals(this.codigoError, cuRPStatus.codigoError) &&
        Objects.equals(this.sessionID, cuRPStatus.sessionID) &&
        Objects.equals(this.resultCURPS, cuRPStatus.resultCURPS);
  }

  @Override
  public int hashCode() {
    return Objects.hash(statusOper, message, tipoError, codigoError, sessionID, resultCURPS);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CURPStatus {\n");
    
    sb.append("    statusOper: ").append(toIndentedString(statusOper)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    tipoError: ").append(toIndentedString(tipoError)).append("\n");
    sb.append("    codigoError: ").append(toIndentedString(codigoError)).append("\n");
    sb.append("    sessionID: ").append(toIndentedString(sessionID)).append("\n");
    sb.append("    resultCURPS: ").append(toIndentedString(resultCURPS)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
