/*
 * API Identity Data
 * <p>Identity Data API es un facilitador de funcionalidades que engloba información de distintas fuentes de acceso públicas y privadas en el progreso del producto para realizar la validación de identidad del Cliente. El objetivo es que a través de una sola API, el usuario puede acceder, corroborar y validar la identidad de la persona haciendo la solicitud de un producto o servicio.</p><br/>
 *
 * OpenAPI spec version: 1.0
 * Contact: api@circulodecredito.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.identityData.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * DataIne
 */

@JsonInclude(JsonInclude.Include.NON_NULL)
public class DataIne {
  @SerializedName("estatus")
  private String estatus = null;

  @SerializedName("mensaje")
  private String mensaje = null;

  @SerializedName("codigoValidacion")
  private String codigoValidacion = null;

  @SerializedName("claveMensaje")
  private String claveMensaje = null;

  @SerializedName("claveElector")
  private String claveElector = null;

  @SerializedName("numeroEmision")
  private String numeroEmision = null;

  @SerializedName("anioRegistro")
  private String anioRegistro = null;

  @SerializedName("anioEmision")
  private String anioEmision = null;

  @SerializedName("vigencia")
  private String vigencia = null;

  @SerializedName("ocr")
  private String ocr = null;

  @SerializedName("cic")
  private String cic = null;

  @SerializedName("distritoFederal")
  private String distritoFederal = null;


  public DataIne estatus(String estatus) {
    this.estatus = estatus;
    return this;
  }

   /**
   * ok, sirva para saber que es correcto el estatus de la credencial
   * @return estatus
  **/
  @Schema(example = "OK", description = "ok, sirva para saber que es correcto el estatus de la credencial")
  public String getEstatus() {
    return estatus;
  }

  public void setEstatus(String estatus) {
    this.estatus = estatus;
  }

  public DataIne mensaje(String mensaje) {
    this.mensaje = mensaje;
    return this;
  }

   /**
   * mnensaje de ine
   * @return mensaje
  **/
  @Schema(example = "Está vigente como medio de identificación y puede votar", description = "mnensaje de ine")
  public String getMensaje() {
    return mensaje;
  }

  public void setMensaje(String mensaje) {
    this.mensaje = mensaje;
  }

  public DataIne codigoValidacion(String codigoValidacion) {
    this.codigoValidacion = codigoValidacion;
    return this;
  }

   /**
   * Código único de ejecución de la validación. El objetivo de este código es guardar un registro de validaciones solicitadas.
   * @return codigoValidacion
  **/
  @Schema(example = "vi1648070031.2717297", description = "Código único de ejecución de la validación. El objetivo de este código es guardar un registro de validaciones solicitadas.")
  public String getCodigoValidacion() {
    return codigoValidacion;
  }

  public void setCodigoValidacion(String codigoValidacion) {
    this.codigoValidacion = codigoValidacion;
  }

  public DataIne claveMensaje(String claveMensaje) {
    this.claveMensaje = claveMensaje;
    return this;
  }

   /**
   * código del mensaje
   * @return claveMensaje
  **/
  @Schema(example = "3", description = "código del mensaje")
  public String getClaveMensaje() {
    return claveMensaje;
  }

  public void setClaveMensaje(String claveMensaje) {
    this.claveMensaje = claveMensaje;
  }

  public DataIne claveElector(String claveElector) {
    this.claveElector = claveElector;
    return this;
  }

   /**
   * Número de clave de elector
   * @return claveElector
  **/
  @Schema(example = "QWERTY12345678M001", description = "Número de clave de elector")
  public String getClaveElector() {
    return claveElector;
  }

  public void setClaveElector(String claveElector) {
    this.claveElector = claveElector;
  }

  public DataIne numeroEmision(String numeroEmision) {
    this.numeroEmision = numeroEmision;
    return this;
  }

   /**
   * Número de emisión de la credencial
   * @return numeroEmision
  **/
  @Schema(example = "4", description = "Número de emisión de la credencial")
  public String getNumeroEmision() {
    return numeroEmision;
  }

  public void setNumeroEmision(String numeroEmision) {
    this.numeroEmision = numeroEmision;
  }

  public DataIne anioRegistro(String anioRegistro) {
    this.anioRegistro = anioRegistro;
    return this;
  }

   /**
   * Año de registro de la credencial
   * @return anioRegistro
  **/
  @Schema(example = "2010", description = "Año de registro de la credencial")
  public String getAnioRegistro() {
    return anioRegistro;
  }

  public void setAnioRegistro(String anioRegistro) {
    this.anioRegistro = anioRegistro;
  }

  public DataIne anioEmision(String anioEmision) {
    this.anioEmision = anioEmision;
    return this;
  }

   /**
   * Año de emisión de la credencial
   * @return anioEmision
  **/
  @Schema(example = "2017", description = "Año de emisión de la credencial")
  public String getAnioEmision() {
    return anioEmision;
  }

  public void setAnioEmision(String anioEmision) {
    this.anioEmision = anioEmision;
  }

  public DataIne vigencia(String vigencia) {
    this.vigencia = vigencia;
    return this;
  }

   /**
   * Vigencia de la credencial
   * @return vigencia
  **/
  @Schema(example = "31 de diciembre de 2027", description = "Vigencia de la credencial")
  public String getVigencia() {
    return vigencia;
  }

  public void setVigencia(String vigencia) {
    this.vigencia = vigencia;
  }

  public DataIne ocr(String ocr) {
    this.ocr = ocr;
    return this;
  }

   /**
   * OCR de la credencial.
   * @return ocr
  **/
  @Schema(example = "1234567890020", description = "OCR de la credencial.")
  public String getOcr() {
    return ocr;
  }

  public void setOcr(String ocr) {
    this.ocr = ocr;
  }

  public DataIne cic(String cic) {
    this.cic = cic;
    return this;
  }

   /**
   * Número CIC de la credencial de elector
   * @return cic
  **/
  @Schema(example = "123456789", description = "Número CIC de la credencial de elector")
  public String getCic() {
    return cic;
  }

  public void setCic(String cic) {
    this.cic = cic;
  }

  public DataIne distritoFederal(String distritoFederal) {
    this.distritoFederal = distritoFederal;
    return this;
  }

   /**
   * Número de distrito federal
   * @return distritoFederal
  **/
  @Schema(example = "11", description = "Número de distrito federal")
  public String getDistritoFederal() {
    return distritoFederal;
  }

  public void setDistritoFederal(String distritoFederal) {
    this.distritoFederal = distritoFederal;
  }






  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DataIne dataIne = (DataIne) o;
    return Objects.equals(this.estatus, dataIne.estatus) &&
        Objects.equals(this.mensaje, dataIne.mensaje) &&
        Objects.equals(this.codigoValidacion, dataIne.codigoValidacion) &&
        Objects.equals(this.claveMensaje, dataIne.claveMensaje) &&
        Objects.equals(this.claveElector, dataIne.claveElector) &&
        Objects.equals(this.numeroEmision, dataIne.numeroEmision) &&
        Objects.equals(this.anioRegistro, dataIne.anioRegistro) &&
        Objects.equals(this.anioEmision, dataIne.anioEmision) &&
        Objects.equals(this.vigencia, dataIne.vigencia) &&
        Objects.equals(this.ocr, dataIne.ocr) &&
        Objects.equals(this.cic, dataIne.cic) &&
        Objects.equals(this.distritoFederal, dataIne.distritoFederal);
  }

  @Override
  public int hashCode() {
    return Objects.hash(estatus, mensaje, codigoValidacion, claveMensaje, claveElector, numeroEmision, anioRegistro, anioEmision, vigencia, ocr, cic, distritoFederal);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DataIne {\n");
    
    sb.append("    estatus: ").append(toIndentedString(estatus)).append("\n");
    sb.append("    mensaje: ").append(toIndentedString(mensaje)).append("\n");
    sb.append("    codigoValidacion: ").append(toIndentedString(codigoValidacion)).append("\n");
    sb.append("    claveMensaje: ").append(toIndentedString(claveMensaje)).append("\n");
    sb.append("    claveElector: ").append(toIndentedString(claveElector)).append("\n");
    sb.append("    numeroEmision: ").append(toIndentedString(numeroEmision)).append("\n");
    sb.append("    anioRegistro: ").append(toIndentedString(anioRegistro)).append("\n");
    sb.append("    anioEmision: ").append(toIndentedString(anioEmision)).append("\n");
    sb.append("    vigencia: ").append(toIndentedString(vigencia)).append("\n");
    sb.append("    ocr: ").append(toIndentedString(ocr)).append("\n");
    sb.append("    cic: ").append(toIndentedString(cic)).append("\n");
    sb.append("    distritoFederal: ").append(toIndentedString(distritoFederal)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
