/*
 * API Identity Data
 * <p>Identity Data API es un facilitador de funcionalidades que engloba información de distintas fuentes de acceso públicas y privadas en el progreso del producto para realizar la validación de identidad del Cliente. El objetivo es que a través de una sola API, el usuario puede acceder, corroborar y validar la identidad de la persona haciendo la solicitud de un producto o servicio.</p><br/>
 *
 * OpenAPI spec version: 1.0
 * Contact: api@circulodecredito.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.identityData.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * DataRenapo
 */


public class DataRenapo {
  @SerializedName("codigoRespuesta")
  private String codigoRespuesta = null;

  @SerializedName("descripcionRespuesta")
  private String descripcionRespuesta = null;

  @SerializedName("referencia")
  private String referencia = null;

  @SerializedName("respuestaRENAPO")
  private RespuestaRENAPO respuestaRENAPO = null;

  public DataRenapo codigoRespuesta(String codigoRespuesta) {
    this.codigoRespuesta = codigoRespuesta;
    return this;
  }

   /**
   * Posibles valores: 00: TRANSACCIÓN EXITOSA 01: SIN RESPUESTA DE RENAPO, 02: SERVIDOR SVBI NO RESPONDE, 03: LOS DATOS SON INCORRECTOS, 04: LA REFERENCIA YA EXISTE, 05: ERROR INESPERADO
   * @return codigoRespuesta
  **/
  @Schema(example = "00", description = "Posibles valores: 00: TRANSACCIÓN EXITOSA 01: SIN RESPUESTA DE RENAPO, 02: SERVIDOR SVBI NO RESPONDE, 03: LOS DATOS SON INCORRECTOS, 04: LA REFERENCIA YA EXISTE, 05: ERROR INESPERADO")
  public String getCodigoRespuesta() {
    return codigoRespuesta;
  }

  public void setCodigoRespuesta(String codigoRespuesta) {
    this.codigoRespuesta = codigoRespuesta;
  }

  public DataRenapo descripcionRespuesta(String descripcionRespuesta) {
    this.descripcionRespuesta = descripcionRespuesta;
    return this;
  }

   /**
   * Posibles valores: -TRANSACCIÓN EXITOSA -SIN RESPUESTA DE RENAPO -SERVIDOR SVBI NO RESPONDE -LOS DATOS SON INCORRECTOS -LA REFERENCIA YA EXISTE -ERROR INESPERADO
   * @return descripcionRespuesta
  **/
  @Schema(example = "TRANSACCION EXITOSA", description = "Posibles valores: -TRANSACCIÓN EXITOSA -SIN RESPUESTA DE RENAPO -SERVIDOR SVBI NO RESPONDE -LOS DATOS SON INCORRECTOS -LA REFERENCIA YA EXISTE -ERROR INESPERADO")
  public String getDescripcionRespuesta() {
    return descripcionRespuesta;
  }

  public void setDescripcionRespuesta(String descripcionRespuesta) {
    this.descripcionRespuesta = descripcionRespuesta;
  }

  public DataRenapo referencia(String referencia) {
    this.referencia = referencia;
    return this;
  }

   /**
   * Get referencia
   * @return referencia
  **/
  @Schema(example = "TEST-CURP02", description = "")
  public String getReferencia() {
    return referencia;
  }

  public void setReferencia(String referencia) {
    this.referencia = referencia;
  }

  public DataRenapo respuestaRENAPO(RespuestaRENAPO respuestaRENAPO) {
    this.respuestaRENAPO = respuestaRENAPO;
    return this;
  }

   /**
   * Get respuestaRENAPO
   * @return respuestaRENAPO
  **/
  @Schema(description = "")
  public RespuestaRENAPO getRespuestaRENAPO() {
    return respuestaRENAPO;
  }

  public void setRespuestaRENAPO(RespuestaRENAPO respuestaRENAPO) {
    this.respuestaRENAPO = respuestaRENAPO;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DataRenapo dataRenapo = (DataRenapo) o;
    return Objects.equals(this.codigoRespuesta, dataRenapo.codigoRespuesta) &&
        Objects.equals(this.descripcionRespuesta, dataRenapo.descripcionRespuesta) &&
        Objects.equals(this.referencia, dataRenapo.referencia) &&
        Objects.equals(this.respuestaRENAPO, dataRenapo.respuestaRENAPO);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codigoRespuesta, descripcionRespuesta, referencia, respuestaRENAPO);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DataRenapo {\n");
    
    sb.append("    codigoRespuesta: ").append(toIndentedString(codigoRespuesta)).append("\n");
    sb.append("    descripcionRespuesta: ").append(toIndentedString(descripcionRespuesta)).append("\n");
    sb.append("    referencia: ").append(toIndentedString(referencia)).append("\n");
    sb.append("    respuestaRENAPO: ").append(toIndentedString(respuestaRENAPO)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
