/*
 * API Identity Data
 * <p>Identity Data API es un facilitador de funcionalidades que engloba información de distintas fuentes de acceso públicas y privadas en el progreso del producto para realizar la validación de identidad del Cliente. El objetivo es que a través de una sola API, el usuario puede acceder, corroborar y validar la identidad de la persona haciendo la solicitud de un producto o servicio.</p><br/>
 *
 * OpenAPI spec version: 1.0
 * Contact: api@circulodecredito.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.identityData.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * RespuestaRENAPO
 */


public class RespuestaRENAPO {
  @SerializedName("CURPStatus")
  private CURPStatus cuRPStatus = null;

  public RespuestaRENAPO cuRPStatus(CURPStatus cuRPStatus) {
    this.cuRPStatus = cuRPStatus;
    return this;
  }

   /**
   * Get cuRPStatus
   * @return cuRPStatus
  **/
  @Schema(description = "")
  public CURPStatus getCuRPStatus() {
    return cuRPStatus;
  }

  public void setCuRPStatus(CURPStatus cuRPStatus) {
    this.cuRPStatus = cuRPStatus;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RespuestaRENAPO respuestaRENAPO = (RespuestaRENAPO) o;
    return Objects.equals(this.cuRPStatus, respuestaRENAPO.cuRPStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cuRPStatus);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RespuestaRENAPO {\n");
    
    sb.append("    cuRPStatus: ").append(toIndentedString(cuRPStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
