/*
 * API Identity Data
 * <p>Identity Data API es un facilitador de funcionalidades que engloba información de distintas fuentes de acceso públicas y privadas en el progreso del producto para realizar la validación de identidad del Cliente. El objetivo es que a través de una sola API, el usuario puede acceder, corroborar y validar la identidad de la persona haciendo la solicitud de un producto o servicio.</p><br/>
 *
 * OpenAPI spec version: 1.0
 * Contact: api@circulodecredito.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.identityData.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * ResultCURPS
 */


public class ResultCURPS {
  @SerializedName("CURP")
  private String CURP = null;

  @SerializedName("apellidoPaterno")
  private String apellidoPaterno = null;

  @SerializedName("apellidoMaterno")
  private String apellidoMaterno = null;

  @SerializedName("nombres")
  private String nombres = null;

  @SerializedName("sexo")
  private String sexo = null;

  @SerializedName("fechNac")
  private String fechNac = null;

  @SerializedName("nacionalidad")
  private String nacionalidad = null;

  @SerializedName("docProbatorio")
  private String docProbatorio = null;

  @SerializedName("anioReg")
  private String anioReg = null;

  @SerializedName("foja")
  private String foja = null;

  @SerializedName("tomo")
  private String tomo = null;

  @SerializedName("libro")
  private String libro = null;

  @SerializedName("numActa")
  private String numActa = null;

  @SerializedName("CRIP")
  private String CRIP = null;

  @SerializedName("numEntidadReg")
  private String numEntidadReg = null;

  @SerializedName("cveMunicipioReg")
  private String cveMunicipioReg = null;

  @SerializedName("numRegExtranjeros")
  private String numRegExtranjeros = null;

  @SerializedName("folioCarta")
  private String folioCarta = null;

  @SerializedName("cveEntidadNac")
  private String cveEntidadNac = null;

  @SerializedName("cveEntidadEmisora")
  private String cveEntidadEmisora = null;

  @SerializedName("statusCurp")
  private String statusCurp = null;

  @SerializedName("FolioCertificado")
  private String folioCertificado = null;

  public ResultCURPS CURP(String CURP) {
    this.CURP = CURP;
    return this;
  }

   /**
   * Get CURP
   * @return CURP
  **/
  @Schema(example = "XXXX910225XXXXXX09", description = "")
  public String getCURP() {
    return CURP;
  }

  public void setCURP(String CURP) {
    this.CURP = CURP;
  }

  public ResultCURPS apellidoPaterno(String apellidoPaterno) {
    this.apellidoPaterno = apellidoPaterno;
    return this;
  }

   /**
   * Get apellidoPaterno
   * @return apellidoPaterno
  **/
  @Schema(example = "XXXX", description = "")
  public String getApellidoPaterno() {
    return apellidoPaterno;
  }

  public void setApellidoPaterno(String apellidoPaterno) {
    this.apellidoPaterno = apellidoPaterno;
  }

  public ResultCURPS apellidoMaterno(String apellidoMaterno) {
    this.apellidoMaterno = apellidoMaterno;
    return this;
  }

   /**
   * Get apellidoMaterno
   * @return apellidoMaterno
  **/
  @Schema(example = "XXXX", description = "")
  public String getApellidoMaterno() {
    return apellidoMaterno;
  }

  public void setApellidoMaterno(String apellidoMaterno) {
    this.apellidoMaterno = apellidoMaterno;
  }

  public ResultCURPS nombres(String nombres) {
    this.nombres = nombres;
    return this;
  }

   /**
   * Get nombres
   * @return nombres
  **/
  @Schema(example = "XXXX", description = "")
  public String getNombres() {
    return nombres;
  }

  public void setNombres(String nombres) {
    this.nombres = nombres;
  }

  public ResultCURPS sexo(String sexo) {
    this.sexo = sexo;
    return this;
  }

   /**
   * Get sexo
   * @return sexo
  **/
  @Schema(example = "H", description = "")
  public String getSexo() {
    return sexo;
  }

  public void setSexo(String sexo) {
    this.sexo = sexo;
  }

  public ResultCURPS fechNac(String fechNac) {
    this.fechNac = fechNac;
    return this;
  }

   /**
   * Get fechNac
   * @return fechNac
  **/
  @Schema(example = "XX/XX/XXXX", description = "")
  public String getFechNac() {
    return fechNac;
  }

  public void setFechNac(String fechNac) {
    this.fechNac = fechNac;
  }

  public ResultCURPS nacionalidad(String nacionalidad) {
    this.nacionalidad = nacionalidad;
    return this;
  }

   /**
   * Get nacionalidad
   * @return nacionalidad
  **/
  @Schema(example = "MEX", description = "")
  public String getNacionalidad() {
    return nacionalidad;
  }

  public void setNacionalidad(String nacionalidad) {
    this.nacionalidad = nacionalidad;
  }

  public ResultCURPS docProbatorio(String docProbatorio) {
    this.docProbatorio = docProbatorio;
    return this;
  }

   /**
   * Get docProbatorio
   * @return docProbatorio
  **/
  @Schema(example = "1", description = "")
  public String getDocProbatorio() {
    return docProbatorio;
  }

  public void setDocProbatorio(String docProbatorio) {
    this.docProbatorio = docProbatorio;
  }

  public ResultCURPS anioReg(String anioReg) {
    this.anioReg = anioReg;
    return this;
  }

   /**
   * Get anioReg
   * @return anioReg
  **/
  @Schema(example = "9999", description = "")
  public String getAnioReg() {
    return anioReg;
  }

  public void setAnioReg(String anioReg) {
    this.anioReg = anioReg;
  }

  public ResultCURPS foja(String foja) {
    this.foja = foja;
    return this;
  }

   /**
   * Get foja
   * @return foja
  **/
  @Schema(description = "")
  public String getFoja() {
    return foja;
  }

  public void setFoja(String foja) {
    this.foja = foja;
  }

  public ResultCURPS tomo(String tomo) {
    this.tomo = tomo;
    return this;
  }

   /**
   * Get tomo
   * @return tomo
  **/
  @Schema(description = "")
  public String getTomo() {
    return tomo;
  }

  public void setTomo(String tomo) {
    this.tomo = tomo;
  }

  public ResultCURPS libro(String libro) {
    this.libro = libro;
    return this;
  }

   /**
   * Get libro
   * @return libro
  **/
  @Schema(example = "9999", description = "")
  public String getLibro() {
    return libro;
  }

  public void setLibro(String libro) {
    this.libro = libro;
  }

  public ResultCURPS numActa(String numActa) {
    this.numActa = numActa;
    return this;
  }

   /**
   * Get numActa
   * @return numActa
  **/
  @Schema(example = "99999", description = "")
  public String getNumActa() {
    return numActa;
  }

  public void setNumActa(String numActa) {
    this.numActa = numActa;
  }

  public ResultCURPS CRIP(String CRIP) {
    this.CRIP = CRIP;
    return this;
  }

   /**
   * Get CRIP
   * @return CRIP
  **/
  @Schema(example = "090050291018921", description = "")
  public String getCRIP() {
    return CRIP;
  }

  public void setCRIP(String CRIP) {
    this.CRIP = CRIP;
  }

  public ResultCURPS numEntidadReg(String numEntidadReg) {
    this.numEntidadReg = numEntidadReg;
    return this;
  }

   /**
   * Get numEntidadReg
   * @return numEntidadReg
  **/
  @Schema(example = "09", description = "")
  public String getNumEntidadReg() {
    return numEntidadReg;
  }

  public void setNumEntidadReg(String numEntidadReg) {
    this.numEntidadReg = numEntidadReg;
  }

  public ResultCURPS cveMunicipioReg(String cveMunicipioReg) {
    this.cveMunicipioReg = cveMunicipioReg;
    return this;
  }

   /**
   * Get cveMunicipioReg
   * @return cveMunicipioReg
  **/
  @Schema(example = "999", description = "")
  public String getCveMunicipioReg() {
    return cveMunicipioReg;
  }

  public void setCveMunicipioReg(String cveMunicipioReg) {
    this.cveMunicipioReg = cveMunicipioReg;
  }

  public ResultCURPS numRegExtranjeros(String numRegExtranjeros) {
    this.numRegExtranjeros = numRegExtranjeros;
    return this;
  }

   /**
   * Get numRegExtranjeros
   * @return numRegExtranjeros
  **/
  @Schema(description = "")
  public String getNumRegExtranjeros() {
    return numRegExtranjeros;
  }

  public void setNumRegExtranjeros(String numRegExtranjeros) {
    this.numRegExtranjeros = numRegExtranjeros;
  }

  public ResultCURPS folioCarta(String folioCarta) {
    this.folioCarta = folioCarta;
    return this;
  }

   /**
   * Get folioCarta
   * @return folioCarta
  **/
  @Schema(description = "")
  public String getFolioCarta() {
    return folioCarta;
  }

  public void setFolioCarta(String folioCarta) {
    this.folioCarta = folioCarta;
  }

  public ResultCURPS cveEntidadNac(String cveEntidadNac) {
    this.cveEntidadNac = cveEntidadNac;
    return this;
  }

   /**
   * Get cveEntidadNac
   * @return cveEntidadNac
  **/
  @Schema(example = "DF", description = "")
  public String getCveEntidadNac() {
    return cveEntidadNac;
  }

  public void setCveEntidadNac(String cveEntidadNac) {
    this.cveEntidadNac = cveEntidadNac;
  }

  public ResultCURPS cveEntidadEmisora(String cveEntidadEmisora) {
    this.cveEntidadEmisora = cveEntidadEmisora;
    return this;
  }

   /**
   * Get cveEntidadEmisora
   * @return cveEntidadEmisora
  **/
  @Schema(example = "99999", description = "")
  public String getCveEntidadEmisora() {
    return cveEntidadEmisora;
  }

  public void setCveEntidadEmisora(String cveEntidadEmisora) {
    this.cveEntidadEmisora = cveEntidadEmisora;
  }

  public ResultCURPS statusCurp(String statusCurp) {
    this.statusCurp = statusCurp;
    return this;
  }

   /**
   * Get statusCurp
   * @return statusCurp
  **/
  @Schema(example = "RCC", description = "")
  public String getStatusCurp() {
    return statusCurp;
  }

  public void setStatusCurp(String statusCurp) {
    this.statusCurp = statusCurp;
  }

  public ResultCURPS folioCertificado(String folioCertificado) {
    this.folioCertificado = folioCertificado;
    return this;
  }

   /**
   * Get folioCertificado
   * @return folioCertificado
  **/
  @Schema(description = "")
  public String getFolioCertificado() {
    return folioCertificado;
  }

  public void setFolioCertificado(String folioCertificado) {
    this.folioCertificado = folioCertificado;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResultCURPS resultCURPS = (ResultCURPS) o;
    return Objects.equals(this.CURP, resultCURPS.CURP) &&
        Objects.equals(this.apellidoPaterno, resultCURPS.apellidoPaterno) &&
        Objects.equals(this.apellidoMaterno, resultCURPS.apellidoMaterno) &&
        Objects.equals(this.nombres, resultCURPS.nombres) &&
        Objects.equals(this.sexo, resultCURPS.sexo) &&
        Objects.equals(this.fechNac, resultCURPS.fechNac) &&
        Objects.equals(this.nacionalidad, resultCURPS.nacionalidad) &&
        Objects.equals(this.docProbatorio, resultCURPS.docProbatorio) &&
        Objects.equals(this.anioReg, resultCURPS.anioReg) &&
        Objects.equals(this.foja, resultCURPS.foja) &&
        Objects.equals(this.tomo, resultCURPS.tomo) &&
        Objects.equals(this.libro, resultCURPS.libro) &&
        Objects.equals(this.numActa, resultCURPS.numActa) &&
        Objects.equals(this.CRIP, resultCURPS.CRIP) &&
        Objects.equals(this.numEntidadReg, resultCURPS.numEntidadReg) &&
        Objects.equals(this.cveMunicipioReg, resultCURPS.cveMunicipioReg) &&
        Objects.equals(this.numRegExtranjeros, resultCURPS.numRegExtranjeros) &&
        Objects.equals(this.folioCarta, resultCURPS.folioCarta) &&
        Objects.equals(this.cveEntidadNac, resultCURPS.cveEntidadNac) &&
        Objects.equals(this.cveEntidadEmisora, resultCURPS.cveEntidadEmisora) &&
        Objects.equals(this.statusCurp, resultCURPS.statusCurp) &&
        Objects.equals(this.folioCertificado, resultCURPS.folioCertificado);
  }

  @Override
  public int hashCode() {
    return Objects.hash(CURP, apellidoPaterno, apellidoMaterno, nombres, sexo, fechNac, nacionalidad, docProbatorio, anioReg, foja, tomo, libro, numActa, CRIP, numEntidadReg, cveMunicipioReg, numRegExtranjeros, folioCarta, cveEntidadNac, cveEntidadEmisora, statusCurp, folioCertificado);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResultCURPS {\n");
    
    sb.append("    CURP: ").append(toIndentedString(CURP)).append("\n");
    sb.append("    apellidoPaterno: ").append(toIndentedString(apellidoPaterno)).append("\n");
    sb.append("    apellidoMaterno: ").append(toIndentedString(apellidoMaterno)).append("\n");
    sb.append("    nombres: ").append(toIndentedString(nombres)).append("\n");
    sb.append("    sexo: ").append(toIndentedString(sexo)).append("\n");
    sb.append("    fechNac: ").append(toIndentedString(fechNac)).append("\n");
    sb.append("    nacionalidad: ").append(toIndentedString(nacionalidad)).append("\n");
    sb.append("    docProbatorio: ").append(toIndentedString(docProbatorio)).append("\n");
    sb.append("    anioReg: ").append(toIndentedString(anioReg)).append("\n");
    sb.append("    foja: ").append(toIndentedString(foja)).append("\n");
    sb.append("    tomo: ").append(toIndentedString(tomo)).append("\n");
    sb.append("    libro: ").append(toIndentedString(libro)).append("\n");
    sb.append("    numActa: ").append(toIndentedString(numActa)).append("\n");
    sb.append("    CRIP: ").append(toIndentedString(CRIP)).append("\n");
    sb.append("    numEntidadReg: ").append(toIndentedString(numEntidadReg)).append("\n");
    sb.append("    cveMunicipioReg: ").append(toIndentedString(cveMunicipioReg)).append("\n");
    sb.append("    numRegExtranjeros: ").append(toIndentedString(numRegExtranjeros)).append("\n");
    sb.append("    folioCarta: ").append(toIndentedString(folioCarta)).append("\n");
    sb.append("    cveEntidadNac: ").append(toIndentedString(cveEntidadNac)).append("\n");
    sb.append("    cveEntidadEmisora: ").append(toIndentedString(cveEntidadEmisora)).append("\n");
    sb.append("    statusCurp: ").append(toIndentedString(statusCurp)).append("\n");
    sb.append("    folioCertificado: ").append(toIndentedString(folioCertificado)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
