/*
 * API Identity Data
 * <p>Identity Data API es un facilitador de funcionalidades que engloba información de distintas fuentes de acceso públicas y privadas en el progreso del producto para realizar la validación de identidad del Cliente. El objetivo es que a través de una sola API, el usuario puede acceder, corroborar y validar la identidad de la persona haciendo la solicitud de un producto o servicio.</p><br/>
 *
 * OpenAPI spec version: 1.0
 * Contact: api@circulodecredito.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.identityData.client.api;

import io.identityData.client.model.Request;
import io.identityData.client.model.ResponseINE;
import io.identityData.client.model.ResponseRenapo;
import io.identityData.client.model.ResponseSEP;
import org.junit.Test;
import org.junit.Ignore;

import java.util.logging.Logger;


/**
 * API tests for FimpeApi
 */
@Ignore
public class IdentityDataApiTest {
    Logger logger = Logger.getLogger("FimpeApiTest");

    private final IdentityDataApi api = new IdentityDataApi();

    /**
     * INE TEST
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void INETest() throws Exception {
        String xApiKey = "YOUR_API_KEY";
        Request body = new Request();
        body.setInfoProvider(Request.InfoProviderEnum.INE);
        body.setCic("");
        body.setOcr("");
        body.setReferencia("");
        body.setInstitucion("");
        body.setFecha("");
        body.setRequestId("");

        ResponseINE response = api.callIneWithHttpInfo(xApiKey, body).getData();
        logger.info("Response final -->" + response);
        // TODO: test validations
    }

    /**
     * SEP TEST
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void SEPTest() throws Exception {
        String xApiKey = "YOUR_API_KEY";
        Request body = new Request();
        body.setInfoProvider(Request.InfoProviderEnum.SEP);

        ResponseSEP responseSEP = api.callSEP(xApiKey, body).getData();
        logger.info("Response final -->" + responseSEP);
        // TODO: test validations
    }

    /**
     * INE TEST
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void RENAPOTest() throws Exception {
        String xApiKey = "YOUR_API_KEY";
        Request body = new Request();
        body.setInfoProvider(Request.InfoProviderEnum.RENAPO);

        ResponseRenapo response = api.callRENAPO(xApiKey, body).getData();
        logger.info("Response final -->" + response);
        // TODO: test validations
    }
}
